# Generated by Django 6.0.3 on 2026-04-20 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('foodType', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('priceRange', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('openingTime', models.TimeField(blank=True, null=True)),
                ('closingTime', models.TimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_truck_images/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_trucks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTruckImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_truck_gallery_images/')),
                ('food_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app.foodtruck')),
            ],
        ),
    ]
